name: Deploy to Avada

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: tomcat deploy  
      #run: curl -v -u avada_kino:OUlIg40qOZ /home/runner/work/Retail/Retail/target/Retail-0.0.1-SNAPSHOT.war 'http://kino.avada-media-dev1.od.ua/manager/html/list?org.apache.catalina.filters.CSRF_NONCE=05E8E8EE19011A332CFFE9DB105C967D'
      #run: curl --upload-file appplication-0.1-1.war "http://tomcat:tomcat@localhost:8080/manager/deploy?path=/application-0.1-1
      #run: curl --upload-file /home/runner/work/Retail/Retail/target/Retail-0.0.1-SNAPSHOT.war 'http://avada_kino:OUlIg40qOZ@kino.avada-media-dev1.od.ua/manager/html/list?org.apache.catalina.filters.CSRF_NONCE=05E8E8EE19011A332CFFE9DB105C967D/&path=/&update=true'
      run: curl -v -u tomcat:OUlIg40qOZ --upload-file /home/runner/work/Retail/Retail/target/Retail-0.0.1-SNAPSHOT.war 'http://avada_kino:OUlIg40qOZ@kino.avada-media-dev1.od.ua/list?org.apache.catalina.filters.CSRF_NONCE=05E8E8EE19011A332CFFE9DB105C967D/&path=/&update=true'
