name: Retail-CI-CD-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME: "retail-admin-app-packages"
  EB_APPLICATION_NAME: "MyRetailAdmin"
  EB_ENVIRONMENT_NAME: "Myretailadmin-env"
  DEPLOY_PACKAGE_NAME: "retail-admin-app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-1"

on:
  push:
    branches: [ "master" ]


jobs:
  ci_aws:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone git repo
        uses: actions/checkout@v3
        
      - name: Create ZIP
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      - name: Configure AWS credentionals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RETAIL_ADMIN_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.RETAIL_ADMIN_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Copy to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
  
  cd_aws:
    runs-on: ubuntu-latest
    needs: [ci_aws]
    
    steps:
      - name: Configure AWS credentionals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RETAIL_ADMIN_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.RETAIL_ADMIN_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      
      - name: Create new application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
          
      - name: Deploy new application version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"
  
  
  
  
  
  
