name: RetilCI

on:
  
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  my-test:
  
    runs-on: ubuntu-latest
    
    steps:

      - name: Run a one-line script
        run: echo Hello, world of test!

  my-deploy:
  
    runs-on: ubuntu-latest
    
    steps:

      - name: Run a one-line script
        run: echo Hello, world of deploy!
